### ISSUE TITLE
You have attempted to set a value of type class java.lang.String for parameter propertyValue with expected type of class java.lang.Integer from query string

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#127] opened 2018-08-27 16:34 UTC
When uploading a file whose field is a relation, even if the column is configured as Integer, it continues to assume the column as String
``
2018-08-27 11:07:49.378 ERROR [http-nio-127.0.0.1-8080-exec-5/mediesfera/admin] de.diedavids.cuba.dataimport.web.importwizard.ImportWizard - An Error occurred during import
com.haulmont.cuba.core.global.RemoteException: You have attempted to set a value of type class java.lang.String for parameter propertyValue with expected type of class java.lang.Integer from query string SELECT e FROM mdsf$SysEnumeracion e where e.codigoEnum = :propertyValue.
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129) ~[cuba-core-6.9.5.jar:6.9.5]
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.sun.proxy.$Proxy187.doDataImport(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) ~[cuba-core-6.9.5.jar:6.9.5]
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) ~[cuba-web-6.9.5.jar:6.9.5]
	at com.sun.proxy.$Proxy314.doDataImport(Unknown Source) ~[na:na]
	at de.diedavids.cuba.dataimport.service.GenericDataImporterService$doDataImport.call(Unknown Source) ~[na:na]
	at de.diedavids.cuba.dataimport.web.importwizard.ImportWizard.startImport(ImportWizard.groovy:229) ~[dataimport-web-0.5.3.jar:na]
[29 - Adicción.xlsx](https://github.com/mariodavid/cuba-component-data-import/files/2324757/29.-.Adiccion.xlsx)
´´

**Comment by mariodavid** [comment] 2018-09-02 16:49
duplicate of #85 . Will close this in favor of the original error.

**Closed by mariodavid** 2018-09-02 16:49 UTC
